<a href="https://colab.research.google.com/github/poorvapuri/UML501/blob/main/Assignment7_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SVM on Iris Dataset

In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

kernels = ['linear', 'poly', 'rbf']

for k in kernels:
    print(f"\n KERNEL: {k.upper()} ")

    if k == 'poly':
        model = SVC(kernel=k, degree=3)
    else:
        model = SVC(kernel=k)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='macro'))
    print("Recall:", recall_score(y_test, y_pred, average='macro'))
    print("F1 Score:", f1_score(y_test, y_pred, average='macro'))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



 KERNEL: LINEAR 
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

 KERNEL: POLY 
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

 KERNEL: RBF 
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


SVM (RBF kernel) model with and without feature scaling

In [4]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


data = load_breast_cancer()
X = data.data
y = data.target


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model_ns = SVC(kernel='rbf')
model_ns.fit(X_train, y_train)

train_acc_ns = model_ns.score(X_train, y_train)
test_acc_ns = model_ns.score(X_test, y_test)

print("\n Without Scaling")
print("Training Accuracy:", train_acc_ns)
print("Testing  Accuracy:", test_acc_ns)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_s = SVC(kernel='rbf')
model_s.fit(X_train_scaled, y_train)

train_acc_s = model_s.score(X_train_scaled, y_train)
test_acc_s = model_s.score(X_test_scaled, y_test)

print("\n With Scaling")
print("Training Accuracy:", train_acc_s)
print("Testing  Accuracy:", test_acc_s)



 Without Scaling
Training Accuracy: 0.9142857142857143
Testing  Accuracy: 0.9473684210526315

 With Scaling
Training Accuracy: 0.989010989010989
Testing  Accuracy: 0.9824561403508771
