<a href="https://colab.research.google.com/github/poorvapuri/UML501/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1 (a) Examine the values of each attribute and Select a set of attributes only that would affect to predict
future bike buyers to create your input for data mining algorithms. Remove all the unnecessary
attributes. (Select features just by analysis)


In [2]:
import pandas as pd
from datetime import datetime

df = pd.read_csv('/content/AWCustomers.csv')

df.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

         Education      Occupation Gender MaritalStatus HomeOwnerFlag  \
0        Bachelors        Clerical      M             M             1   
1  Partial College        Clerical      M             M             1   
2        Bachelors        Clerical      F             S             0   
3  Partial College  Skilled Manual      M             M             1   
4  Partial College  Skilled Manual      M             S             1   

  NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
0               3                    0             1         81916   
1               2                    1             2         81076   
2               3                    0             0         86387   
3               2                    1             2         61481   
4               1                    0             0         51804   

   LastUpdated  
0   2017-03-06  
1   2017-03-06  
2   2017-03-06  
3   2017-03-06  
4   2017-03-06  

[5 rows x 24 columns]

(b) Create a new Data Frame with the selected attributes only.


In [4]:
df = pd.read_csv('/content/AWCustomers.csv')

col_remove = ['CustomerID', 'Title','FirstName', 'AddressLine1', 'LastName', 'MiddleName', 'Suffix' ,'AddressLine2', 'StateProvinceName', 'PostalCode', 'PhoneNumber', 'LastUpdated', 'CountryRegionName']
df = df.drop(columns=col_remove)

df['BirthDate'] = pd.to_datetime(df['BirthDate'])
today = pd.to_datetime('today')
df['Age'] = today.year - df['BirthDate'].dt.year
df['Age'] -= ((today.month < df['BirthDate'].dt.month) | ((today.month == df['BirthDate'].dt.month) & (today.day < df['BirthDate'].dt.day)))
df = df.drop(columns=['BirthDate'])

df.to_csv('selected.csv', index=False)
df.head()

City        Education      Occupation Gender MaritalStatus  \
0   Wollongong        Bachelors        Clerical      M             M   
1      Shawnee  Partial College        Clerical      M             M   
2  West Covina        Bachelors        Clerical      F             S   
3    Liverpool  Partial College  Skilled Manual      M             M   
4        Werne  Partial College  Skilled Manual      M             S   

   HomeOwnerFlag  NumberCarsOwned  NumberChildrenAtHome  TotalChildren  \
0              1                3                     0              1   
1              1                2                     1              2   
2              0                3                     0              0   
3              1                2                     1              2   
4              1                1                     0              0   

   YearlyIncome  Age  
0         81916   37  
1         81076   53  
2         86387   39  
3         61481   47  
4         51804   50

(c) Determine a Data value type (Discrete, or Continuous, then Nominal, Ordinal, Interval, Ratio) of
each attribute in your selection to identify preprocessing tasks to create input for your data mining



City: Nominal (Discrete)
Education: Ordinal (Discrete)
Occupation: Nominal (Discrete)
Gender: Nominal (Discrete)
MaritalStatus: Nominal (Discrete)
HomeOwnerFlag: Nominal (Discrete)
NumberCarsOwned: Ratio (Discrete)
NumberChildrenAtHome: Ratio (Discrete)
TotalChildren: Ratio (Discrete)
YearlyIncome: Ratio (Continuous)
Age: Ratio (Continuous)


Part II: Data Preprocessing and Transformation
Depending on the data type of each attribute, transform each object from your preprocessed data.
Use all the data rows (~= 18000 rows) with the selected features as input to apply all the tasks below, do
not perform each task on the smaller data set that you got from your random sampling result.
(a) Handling Null values

In [5]:
df = pd.read_csv('selected.csv')
print(f"{df.isnull().sum()}")

null_cols = df.columns[df.isnull().sum() > 0]
print(f"Null Columns =  {null_cols}")
df['NumberCarsOwned'] = df['NumberCarsOwned'].fillna(df['NumberCarsOwned'].mean())
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

print(f"{df.isnull().sum()}")

City                    0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
Age                     0
dtype: int64
Null Columns =  Index([], dtype='object')
City                    0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
Age                     0
dtype: int64


(b) Normalization

In [6]:
numeric_cols = ['NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome']
for i in numeric_cols:
    df[i] = (df[i] - df[i].min()) / (df[i].max() - df[i].min())
    print(f"Normalized {i} = \n{df[i]}")

Normalized NumberCarsOwned = 
0        0.6
1        0.4
2        0.6
3        0.4
4        0.2
        ... 
18356    0.2
18357    0.4
18358    0.4
18359    0.0
18360    0.4
Name: NumberCarsOwned, Length: 18361, dtype: float64
Normalized NumberChildrenAtHome = 
0        0.000000
1        0.333333
2        0.000000
3        0.333333
4        0.000000
           ...   
18356    0.000000
18357    0.000000
18358    0.000000
18359    0.000000
18360    0.000000
Name: NumberChildrenAtHome, Length: 18361, dtype: float64
Normalized TotalChildren = 
0        0.333333
1        0.666667
2        0.000000
3        0.666667
4        0.000000
           ...   
18356    0.666667
18357    0.000000
18358    0.000000
18359    0.000000
18360    0.000000
Name: TotalChildren, Length: 18361, dtype: float64
Normalized YearlyIncome = 
0        0.496842
1        0.489453
2        0.536172
3        0.317083
4        0.231958
           ...   
18356    0.242065
18357    0.312781
18358    0.232442
18359    0.543121

(c) Discretization (Binning) on Continuous attributes or Categorical Attributes with too many different
values

In [7]:
df['Income_Bin'] = pd.cut(df['YearlyIncome'], bins=4, labels=[1, 2, 3, 4])
print(f"Income_Bin = \n{df['Income_Bin']}")

Income_Bin = 
0        2
1        2
2        3
3        2
4        1
        ..
18356    1
18357    2
18358    1
18359    3
18360    4
Name: Income_Bin, Length: 18361, dtype: category
Categories (4, int64): [1 < 2 < 3 < 4]


(d) Standardization/Normalization

In [9]:
for col in numeric_cols:
    df[col + '_std'] = (df[col] - df[col].mean()) / df[col].std()
    print(f"Std = \n{df[col + '_std']}")

Std = 
0        1.892473
1        0.798367
2        1.892473
3        0.798367
4       -0.295738
           ...   
18356   -0.295738
18357    0.798367
18358    0.798367
18359   -1.389843
18360    0.798367
Name: NumberCarsOwned_std, Length: 18361, dtype: float64
Std = 
0       -0.594355
1        1.163248
2       -0.594355
3        1.163248
4       -0.594355
           ...   
18356   -0.594355
18357   -0.594355
18358   -0.594355
18359   -0.594355
18360   -0.594355
Name: NumberChildrenAtHome_std, Length: 18361, dtype: float64
Std = 
0        0.161337
1        1.239719
2       -0.917044
3        1.239719
4       -0.917044
           ...   
18356    1.239719
18357   -0.917044
18358   -0.917044
18359   -0.917044
18360   -0.917044
Name: TotalChildren_std, Length: 18361, dtype: float64
Std = 
0        0.298547
1        0.271173
2        0.444249
3       -0.367391
4       -0.682747
           ...   
18356   -0.645303
18357   -0.383327
18358   -0.680955
18359    0.469993
18360    2.088939
Name: 

(e) Binarization (One Hot Encoding)

In [10]:
pd.set_option('display.max_columns', None)
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
arr = encoder.fit_transform(df[['Gender', 'MaritalStatus', 'Education', 'Occupation']]).toarray()
df = pd.DataFrame(arr, columns=encoder.get_feature_names_out(['Gender', 'MaritalStatus', 'Education', 'Occupation']))

df.head()

Gender_F  Gender_M  MaritalStatus_M  MaritalStatus_S  Education_Bachelors  \
0       0.0       1.0              1.0              0.0                  1.0   
1       0.0       1.0              1.0              0.0                  0.0   
2       1.0       0.0              0.0              1.0                  1.0   
3       0.0       1.0              1.0              0.0                  0.0   
4       0.0       1.0              0.0              1.0                  0.0   

   Education_Graduate Degree  Education_High School  \
0                        0.0                    0.0   
1                        0.0                    0.0   
2                        0.0                    0.0   
3                        0.0                    0.0   
4                        0.0                    0.0   

   Education_Partial College  Education_Partial High School  \
0                        0.0                            0.0   
1                        1.0                            0.0   
2                        0.0                            0.0   
3                        1.0                            0.0   
4                        1.0                            0.0   

   Occupation_Clerical  Occupation_Management  Occupation_Manual  \
0                  1.0                    0.0                0.0   
1                  1.0                    0.0                0.0   
2                  1.0                    0.0                0.0   
3                  0.0                    0.0                0.0   
4                  0.0                    0.0                0.0   

   Occupation_Professional  Occupation_Skilled Manual  
0                      0.0                        0.0  
1                      0.0                        0.0  
2                      0.0                        0.0  
3                      0.0                        1.0  
4                      0.0                        1.0

Part III: Calculating Proximity /Correlation Analysis of two features
Make sure each attribute is transformed in a same scale for numeric attributes and Binarization for each
nominal attribute, and each discretized numeric attribute to standardization. Make sure to apply a correct
similarity measure for nominal (one hot encoding)/binary attributes and numeric attributes respectively.

(a) Calculate Similarity in Simple Matching, Jaccard Similarity, and Cosine Similarity between two
following objects of your transformed input data.

In [11]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from numpy import dot
from numpy.linalg import norm

df = pd.read_csv('selected.csv')

num_cols = ['YearlyIncome','Age','NumberCarsOwned','NumberChildrenAtHome','TotalChildren','HomeOwnerFlag']
cat_cols = ['City','Education','Occupation','Gender','MaritalStatus']

scaler = StandardScaler()
numeric = scaler.fit_transform(df[num_cols])

encoder = OneHotEncoder(sparse_output=False)
nominal = encoder.fit_transform(df[cat_cols])

X = np.hstack([numeric, nominal])
obj1 = X[0]
obj2 = X[1]

simple_matching = np.sum(obj1==obj2)/len(obj1)
jaccard = np.sum((obj1>0)&(obj2>0))/np.sum((obj1>0)|(obj2>0))
cosine = dot(obj1,obj2)/(norm(obj1)*norm(obj2))

simple_matching, jaccard, cosine
print(f"Matching = {simple_matching}")
print(f"Jaccard = {jaccard}")
print(f"Cosine = {cosine}")

Matching = 0.9688581314878892
Jaccard = 0.5384615384615384
Cosine = 0.4263347919106479


(b) Calculate Correlation between two features Commute Distance and Yearly Income

In [12]:
corr = df['YearlyIncome'].corr(df['Age'])
print(f"Correlation = {corr}")

Correlation = 0.02638715122126233
